# Generated by Django 5.1.3 on 2024-11-27 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulario',
            name='horario',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
