# Generated by Django 5.1.3 on 2024-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_formulario_data_formulario_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='servicos',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='horario',
            field=models.TimeField(),
        ),
    ]
